name: Backstage Docker Build and push to ACR

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      # 3. Install dependencies
      - name: Install dependencies
        run: yarn install --immutable

      # 4. Build Backstage backend
      - name: Build Backstage
        run: |
          yarn tsc
          yarn build:backend

      # 5. Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t backstage:local -f packages/backend/Dockerfile .

      # 6. Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 7. Login to ACR
      - name: Login to Azure Container Registry
        run: |
          az acr login --name BackstageAcr12

      # 8. Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag backstage:local BackstageAcr12.azurecr.io/backstage:latest

      # 9. Push Docker Image to ACR
      - name: Push Docker Image
        run: |
          docker push <YOUR_ACR_NAME>.azurecr.io/backstage:latest
